name: ci

on: [push]
  # schedule:
  # - cron: '0 0 * * *'

jobs:
  fuzzit_fuzzing:
    runs-on: ubuntu-latest
    container:
      image: fuzzitdev/golang:1.12.7-buster
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Docker Client
        run: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
      - name: Sym Link Expected Path to Workspace
        run: |
          mkdir -p /go/src/github.com/prometheus/prometheus
          ln -s $GITHUB_WORKSPACE/* /go/src/github.com/prometheus/prometheus
      - name: Fuzzing
        run: ./fuzzit.sh fuzzing
        working-directory: /go/src/github.com/prometheus/prometheus
  
  repo_sync:
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:1.15-node
    steps:
      - name: Permission Setup
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Sync Repository
        run: ./scripts/sync_repo_files.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}