name: ci

on: [push]
  # schedule:
  # - cron: '0 0 * * *'

jobs:
  fuzzit_fuzzing:
    runs-on: ubuntu-latest
    container:
      image: fuzzitdev/golang:1.12.7-buster
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Fuzzing
        run: ./fuzzit.sh fuzzing
  
  repo_sync:
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:1.15-node
    steps:
      - name: Permission Setup
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Sync Repository
        run: ./scripts/sync_repo_files.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}