name: ci

on:
  schedule:
  - cron: '0 0 * * *'
  push:
    # branches: [ master ]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:1.15-node
    steps:
      - name: setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: checkout repo
        uses: actions/checkout@v2
      - name: make promu
        run: make promu
      - name: load go modules cache
        uses: actions/cache@v2
        with:
          path: /home/circleci/go/pkg/mod
          key: v1-{{ arch }}-{{ checksum "go.sum" }}
      - name: load yarn cache
        uses: actions/cache@v2
        with:
          path: /home/circleci/.cache/yarn
          key: v3-npm-deps-{{ checksum "web/ui/react-app/yarn.lock" }}--{{ arch }}-{{ checksum "go.sum"  }}
          restore-keys: v3-npm-deps--{{ arch }}-{{ checksum "go.sum"  }}
      # - run: make
      #   env:
      #     GOGC: "20"
      #     GOOPTS: "-p 2"
      #     GOMAXPROCS: "2"
      - name: prometheus/check_proto
        env:
          VERSION: 3.12.3
        run: |
          curl -s -L \
          https://github.com/protocolbuffers/protobuf/releases/download/v${VERSION}/protoc-${VERSION}-linux-x86_64.zip > /tmp/protoc.zip
          unzip -d /tmp /tmp/protoc.zip
          chmod +x /tmp/bin/protoc
          echo 'export PATH=/tmp/bin:$PATH' >> $BASH_ENV
          source $BASH_ENV
          make proto
          git diff --exit-code
      - name: prometheus/store_artifact prometheus
        uses: actions/upload-artifact@v2
        with:
          name: prometheus
          path: /build/prometheus
      - name: prometheus/store_artifact promtool
        uses: actions/upload-artifact@v2
        with:
          name: promtool
          path: /build/promtool
