name: ci

on:
  schedule:
  - cron: '0 0 * * *'
  push:
    # branches: [ master ]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: circleci/golang:1.15-node
    steps:
      - name: setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: checkout repo
        uses: actions/checkout@v2
      - name: make promu
        run: make promu
      - name: cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: v3-npm-deps yarnlock
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v3-npm-deps-{{ checksum "web/ui/react-app/yarn.lock" }}--{{ arch }}-{{ checksum "go.sum"  }}
          restore-keys: v3-npm-deps--{{ arch }}-{{ checksum "go.sum"  }}
      # - run: make
      #   env: 
      #     GOGC: "20"
      #     GOOPTS: "-p 2"
      #     GOMAXPROCS: "2"
      # - name: prometheus/check_proto
      #   run: |
      #     curl -s -L \
      #     https://github.com/protocolbuffers/protobuf/releases/download/v<<
      #     parameters.version >>/protoc-<< parameters.version >>-linux-x86_64.zip > /tmp/protoc.zip
      #     unzip -d /tmp /tmp/protoc.zip
      #     chmod +x /tmp/bin/protoc
      #     echo 'export PATH=/tmp/bin:$PATH' >> $BASH_ENV
      #     source $BASH_ENV
      #     make proto
      #     git diff --exit-code